name: CI Pipeline

on:
  push:
    branches: [ main, develop, feat/add-github-pipeline]
  pull_request:
    branches: [ main, develop, feat/add-github-pipeline]

jobs:
  install:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 18.x]

    steps:
      - name: Set up Node.js environnement
        uses: ./.github/workflows/common-setup.yml

      - name: Install dependencies
        run: npm ci

      - name: Upload node_modules
        uses: actions/upload-artifact@v4
        with:
          name: node_modules-${{ matrix.node-version }}
          path: node_modules

  lint:
    runs-on: ubuntu-latest
    needs: install

    strategy:
      matrix:
        node-version: [20.x, 18.x]

    steps:
      - name: Set up Node.js environnement
        uses: ./.github/workflows/common-setup.yml

      - name: Download node_modules
        uses: actions/download-artifact@v4
        with:
          name: node_modules-${{ matrix.node-version }}
          path: node_modules

      - name: Run ESLint
        run: npm run lint

  unit-tests:
    runs-on: ubuntu-latest
    needs: install

    strategy:
      matrix:
        node-version: [20.x, 18.x]

    steps:
      - name: Set up Node.js environnement
        uses: ./.github/workflows/common-setup.yml

      - name: Download node_modules
        uses: actions/download-artifact@v4
        with:
          name: node_modules-${{ matrix.node-version }}
          path: node_modules

      - name: Run unit tests
        run: npm run test:unit

  e2e-tests:
    runs-on: ubuntu-latest
    needs: install

    strategy:
      matrix:
        node-version: [20.x, 18.x]

    steps:
      - name: Set up Node.js environnement
        uses: ./.github/workflows/common-setup.yml

      - name: Download node_modules
        uses: actions/download-artifact@v4
        with:
          name: node_modules-${{ matrix.node-version }}
          path: node_modules

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run end-to-end tests
        run: npm run test:e2e

      - name: Save end-to-end tests report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30